@startuml

skin rose

class World {
    +growPeople()
    +initializeLibrary()
}

class Person {
    +name: String
    +email: String
    +clientType: String
    +previousLoans: List<Loan>
}

class Library {
    +manageLoans()
    +showMaterials()
}

abstract class Material {
    +type: String
    +isAvailable: Boolean
}

class Book {
    +author: String
    +pages: int
}

class DVD {
    +duration: int
    +director: String
}

class Classroom {
    +roomNumber: String
    +capacity: int
}

class Loan {
    +useExistingMaterial(Material)
}

World *-- "many" Person : "grows"
World *-- "1" Library : "initializes"
Person --> "1" Library : "visits"
Library .. "0..*" Loan : "manages"
Library o-- "1..*" Material : "stores"
Loan --> "1" Material : "uses"

Material <|-- Book
Material <|-- DVD
Material <|-- Classroom

@enduml

